<?php

namespace Sport\BackofficeBundle\Repository;

/**
 * PhotoCategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoCategorieRepository extends \Doctrine\ORM\EntityRepository
{
}
